# Generated by Django 4.2.6 on 2023-10-08 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoExampleApp', '0002_alter_news_id_alter_profile_roles_alter_role_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
